### ISSUE TITLE
Need help getting the fragment to work

### ISSUE THREAD

**Issue by Grkmk** [MartinBeuriot/insomnia-plugin-gql-fragments#1]
Hey!

I'm trying to use the plugin, but can't get it to work. I'm guessing it's a misunderstanding on my part. Could you let me know what I'm doing wrong?

![Screen Shot 2022-07-18 at 12 52 26](https://user-images.githubusercontent.com/52107130/179487348-3f761aad-15e7-4b34-8304-abeeff56263d.png)

So, I have this fragment:
![Screen Shot 2022-07-18 at 12 42 00](https://user-images.githubusercontent.com/52107130/179485473-724a20c0-a532-4d89-b459-915ed9154778.png)

Inside my query, I've tried (omitting the unrelated query stuff):
- `{% fragment 'UserFragment' %}`
- `{% fragment "UserFragment" %}`
- `... UserFragment`,
- `UserFragment` 
etc.

The error message I get (some of the time) is `"Unknown fragment \"fragment\".`.

**Comment by MartinBeuriot** [comment]
I think you got the incorrect syntax it should be `{% fragment 'req_63a754160eae4b43ba4eda41a465af27' %}`
If you right click on the request where the fragment is declared there should be a menu to grab that code 

<img width="219" alt="image" src="https://user-images.githubusercontent.com/83237796/179529879-25293f63-901c-4b31-b6f9-6e04312f0083.png">

<img width="770" alt="image" src="https://user-images.githubusercontent.com/83237796/179529930-55aaf81c-95a4-4101-81d2-4af6737913b4.png">

hope that helps

**Comment by MartinBeuriot** [comment]
in one request you can define your fragment
```
fragment userFragment on Used {
  __typename
  id
  name
  email
```
get this request url
then in your main query should be something like:
```
query userByEmail($id: ID!) {
  user(id: $id) {
    somting {
      ...userFragment
    }
  }
}

#User Fragment
{% fragment 'req_xxxxxxxxxxxxxxxxxx' %}

**Comment by Grkmk** [comment]
still no luck

1. created a request for fragment with `plain` body
![Screen Shot 2022-07-19 at 10 02 16](https://user-images.githubusercontent.com/52107130/179687712-e1410ce8-a5c3-45f0-8d96-63ed7c92982d.png)

2. got its request id
![Screen Shot 2022-07-19 at 10 02 26](https://user-images.githubusercontent.com/52107130/179687716-8dc6e9ae-786a-4aef-b77e-f2f6dfe26158.png)

3a. tried with the full fragment url
![Screen Shot 2022-07-19 at 10 03 08](https://user-images.githubusercontent.com/52107130/179687718-74ec89bb-1a54-4a4e-81c8-c7a3fe5dc561.png)

3b. tried with the partial fragment url
![Screen Shot 2022-07-19 at 10 03 27](https://user-images.githubusercontent.com/52107130/179687720-50e661bb-70ff-4a6f-94b2-976ee26b6dbc.png)


btw, here is my insomnia version, maybe that's the issue 🤷 
```
Version: Insomnia 2022.4.2
Build date: 6/22/2022
OS: Darwin arm64 20.6.0
Electron: 18.1.0
Node: 16.13.2
V8: 10.0.139.15-electron.0
Architecture: arm64
```

**Comment by MartinBeuriot** [comment]
I think I was able to reproduce the issue on my end with plain text too. Try using structured as graphql query instead of plain text and it should work.

**Comment by Grkmk** [comment]
Yes, I was able to get it to work after using the graphql type. Thanks for the help!

On a side note, there were other things in my implementation that were causing issues:
- comments aren't being handled if they are inside the fragment declaration (causing `"unexpected <EOF>"` errors)
- newlines between fields were ignored (i.e. if the fragment had fields `id` & `name` separated by newline, it would actually be parsed & requested as `idname`). so my solution was to comma separate or add a space after each field.

If you can point me to code blocks responsible for these, I would be happy to make a pr.

**Comment by MartinBeuriot** [comment]
oh ok, glad you got it working.
https://github.com/MartinBeuriot/insomnia-plugin-gql-fragments/blob/master/src/template-tags/frag.ts#L24

**Comment by Grkmk** [comment]
I made some minor changes, but I'm unable to push my current branch (not master). Can you update the repo's access settings? I'll make a pr for you to review right after.
